Updates to tutorial in-line with truffle changes
'start.sh' and 'init.sh' have been changed to 'raft-start.sh' and 'raft-init.sh' respectively.
truffle init no longer requires a project name.
Omitting gas and gasPrice results in:
   Error encountered, bailing. Network state unknown. Review successful  transactions manually.
   Error: Gas price not 0